# Generated by Django 4.1.7 on 2023-05-30 09:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bovine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distinctiveTrait', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('is_female', models.BooleanField(default=False)),
                ('dateOfBirth', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfRecord', models.DateTimeField()),
                ('WeightRecord', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bovine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bovine.bovine')),
            ],
        ),
        migrations.CreateModel(
            name='BovineHeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('term', models.DateTimeField()),
                ('is_current', models.BooleanField(default=False)),
                ('bovine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bovine.bovine')),
            ],
        ),
    ]
