# Generated by Django 4.1.7 on 2023-05-30 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahorro',
            name='monto_obj',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
